version: '3'
services:
  openresty:
    image: openresty/openresty:latest
    ports:
    - 9191:9191
    volumes:
      - ./openresty/libs:/etc/nginx/lua/resty
      - ./openresty/pages:/etc/nginx/lua/pages
      - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
  redis:
    image: redis:4.0
    command: "redis-server --notify-keyspace-events KEgx --loglevel debug"
    volumes:
      - redis:/data
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
  # программа на го удаляет истекшие ключи из очереди
  watcher:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./app:/src
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
volumes:
  redis:
